#!/bin/bash
# usage: watch.sh <your_command> <sleep_duration>

TIME=2

FIRST_ARG=$1
if [ "$FIRST_ARG" = "-n" ]
then
  shift 
  TIME=$1
  shift
fi

while :;
  do
  clear
  
  date
  echo
  
  $@
  sleep $TIME
done


